user_name : y446970841@163.com
pass_word : 1122000

chromedrive_path: /usr/bin/chromedriver
#chromedrive_path: D:\\bilibiliupload\\chromedriver.exe

links_id:
    星际2INnoVation吕布卫星人族天梯第一视角:
        - https://www.twitch.tv/innovation_s2
        - https://www.panda.tv/1160340
    星际2soO输本虫族天梯第一视角:
        - https://www.twitch.tv/sc2soo
        - https://www.panda.tv/1150595
    星际2sOs狗哥神族天梯第一视角:
        - https://www.panda.tv/1160930
        - https://www.twitch.tv/zx2362
    星际2Stats拔本神族天梯第一视角:
        - https://www.twitch.tv/kimdaeyeob3
    星际2Dark暗本虫族天梯第一视角:
        - https://www.twitch.tv/qkrfuddn0
    星际2Scarlett噶姐虫族天梯第一视角:
        - https://www.twitch.tv/scarlettm
    星际2GuMiho砸本人族天梯第一视角:
        - https://www.twitch.tv/gumiho
    星际2Maru人族天梯第一视角:
        - https://www.twitch.tv/maru072
    星际2TY全教主全太阳人族天梯第一视角:
        - https://www.twitch.tv/sc2tyty
    星际2ByuN武圣人族天梯第一视角:
        - https://www.twitch.tv/byunprime
    星际2小herO神族天梯第一视角:
        - https://www.twitch.tv/dmadkr0818
    星际2Zest神族天梯第一视角:
        - https://www.twitch.tv/sc2_zest
    星际2PartinG跳跳胖丁神族天梯第一视角:
        - https://www.twitch.tv/partingthebigboy
    星际2Rogue脑虫虫族天梯第一视角:
        - https://www.twitch.tv/roguejinair
#    test:
#        - https://www.twitch.tv/roguejinair
#        - https://www.panda.tv/2068335
#    测试:
#        - https://www.douyu.com/scboy
#        - https://www.panda.tv/15109

# root_url:
#     https://www.twitch.tv/https://www.twitch.tv/
#     https://www.panda.tv/https://www.panda.tv/
#     Douyu: https://www.douyu.com/
#     Twitch_check: https://api.twitch.tv/kraken/streams/
#     Douyu_check: http://open.douyucdn.cn/api/RoomApi/room/